{{module_name}}.o: {{module_name}}.c  
	gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I /Users/xingyue/outcode/source/nginx-1.6.0/src/core -I /Users/xingyue/outcode/source/nginx-1.6.0/src/event -I /Users/xingyue/outcode/source/nginx-1.6.0/src/event/modules -I /Users/xingyue/outcode/source/nginx-1.6.0/src/os/unix -I /Users/xingyue/outcode/source/nginx-1.6.0/objs -I /Users/xingyue/outcode/source/nginx-1.6.0/src/http -I /Users/xingyue/outcode/source/nginx-1.6.0/src/http/modules -I /Users/xingyue/outcode/source/nginx-1.6.0/mail -o ngx_http_ishare_module.o {{module_name}}.c 
clean:
	rm -f {{module_name}}.o
