ngx_http_redis_module.o: ngx_http_redis_module.c  
	    gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I /data0/zyq/nginx-1.7.3/src/core -I /data0/zyq/nginx-1.7.3/src/event -I /data0/zyq/nginx-1.7.3/src/event/modules -I /data0/zyq/nginx-1.7.3/src/os/unix -I /data0/zyq/nginx-1.7.3/objs -I /data0/zyq/nginx-1.7.3/src/http -I /data0/zyq/nginx-1.7.3/src/http/modules -I /data0/zyq/nginx-1.7.3/src/mail -o ngx_http_redis_module.o /data0/zyq/nginx-1.7.3/ngx_http_redis_module/ngx_http_redis_module.c 
clean:
	rm -f ngx_http_redis_module.o
